apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: forgejo-db
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: pg-fqdn
    - secretKey: db_user
      remoteRef:
        key: pg-admin-username
    - secretKey: db_password
      remoteRef:
        key: pg-admin-password
