---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-token
  namespace: forgejo-runner
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: forgejo-runner-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CONFIG_NAME: "forgejo-runner"
        CONFIG_INSTANCE: "http://forgejo-http.forgejo.svc.cluster.local:3000"
        CONFIG_TOKEN: "{{ .registration_token }}"
  data:
    - secretKey: registration_token
      remoteRef:
        key: forgejo-runner-registration-token
