#!/usr/bin/env bash
# hq.kevinryan.io theme sync — single source of truth flow.
#
# Regenerates k8s/hq-kevinryan-io/configmap-custom-theme.yaml from the
# source files in sites/hq-kevinryan-io/ and derives the custom-theme.css
# cache-buster (?v=<first 8 of sha256>) in k8s/hq-kevinryan-io/deployment.yaml.
#
# The ConfigMap is GENERATED. Never edit it by hand — edit the sources and
# re-run this script.
#
# Usage:
#   scripts/sync-hq-theme.sh          regenerate ConfigMap + cache-buster
#   scripts/sync-hq-theme.sh --check  verify committed state matches the
#                                     sources; exit 1 on drift (used by CI)
#
# Requires: kubectl (offline — --dry-run=client, no cluster needed).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SITE="$ROOT/sites/hq-kevinryan-io"
K8S="$ROOT/k8s/hq-kevinryan-io"
CM="$K8S/configmap-custom-theme.yaml"
DEPLOY="$K8S/deployment.yaml"
FAV="$SITE/favicons"

# ── Sources (adding a new asset? add it here AND to the skill docs) ──
SOURCES=(
  "custom-theme.css=$SITE/custom-theme.css"
  "logo.svg=$SITE/logo.svg"
  "favicon.ico=$FAV/favicon.ico"
  "favicon-16x16.png=$FAV/favicon-16x16.png"
  "favicon-32x32.png=$FAV/favicon-32x32.png"
  "apple-touch-icon-180x180.png=$FAV/apple-touch-icon-180x180.png"
)

for entry in "${SOURCES[@]}"; do
  f="${entry#*=}"
  [ -f "$f" ] || { echo "FATAL: missing source file: $f" >&2; exit 1; }
done

CSS="$SITE/custom-theme.css"

# ── Cache-buster: content hash of the CSS ──
# Changes exactly when the CSS content changes, so the service worker
# cache is busted if — and only if — the theme actually changed. No more
# manual ?v=N bumps.
hash_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | cut -d' ' -f1
  else
    shasum -a 256 "$1" | cut -d' ' -f1
  fi
}
V="$(hash_file "$CSS" | cut -c1-8)"

# ── Generate the ConfigMap ──
from_file_args=()
for entry in "${SOURCES[@]}"; do
  from_file_args+=(--from-file="$entry")
done

generate() {
  {
    echo "# Generated by scripts/sync-hq-theme.sh — DO NOT EDIT."
    echo "# Sources live in sites/hq-kevinryan-io/ (custom-theme.css,"
    echo "# logo.svg, favicons/). Edit those and re-run the script."
    kubectl create configmap librechat-custom \
      --namespace hq-kevinryan-io \
      "${from_file_args[@]}" \
      --dry-run=client -o yaml \
      | grep -v '^  creationTimestamp: null$'
  }
}

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
generate > "$TMP"

if [ "${1:-}" = "--check" ]; then
  # CI drift check: committed ConfigMap must equal the generated one, and
  # the deployment cache-buster must equal the current CSS hash.
  ok=1
  if ! diff -u "$CM" "$TMP"; then
    echo "FATAL: $CM is out of sync with sites/hq-kevinryan-io/" >&2
    ok=0
  fi
  if ! grep -q "custom-theme.css?v=$V" "$DEPLOY"; then
    echo "FATAL: $DEPLOY cache-buster stale — expected ?v=$V" >&2
    ok=0
  fi
  if [ "$ok" -eq 1 ]; then
    echo "hq theme in sync (v=$V)"
  else
    echo "Drift detected — run: scripts/sync-hq-theme.sh" >&2
    exit 1
  fi
else
  cp "$TMP" "$CM"
  # Rewrite the cache-buster in the patch-index sed (portable in-place sed).
  sed "s|custom-theme.css?v=[0-9a-f][0-9a-f]*|custom-theme.css?v=$V|g" \
    "$DEPLOY" > "$DEPLOY.tmp" && mv "$DEPLOY.tmp" "$DEPLOY"
  echo "Regenerated $CM"
  echo "Cache-buster: ?v=$V"
fi
