apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: librechat-secrets
  namespace: hq-kevinryan-io
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: librechat-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: librechat-jwt-secret
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: librechat-jwt-refresh-secret
    - secretKey: CREDS_KEY
      remoteRef:
        key: librechat-creds-key
    - secretKey: CREDS_IV
      remoteRef:
        key: librechat-creds-iv
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: anthropic-api-key
