apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: directus-secrets
  namespace: directus
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: directus-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_CLIENT: "pg"
        DB_HOST: "{{ .pg_fqdn }}"
        DB_PORT: "5432"
        DB_DATABASE: "directus_db"
        DB_USER: "{{ .pg_admin_username }}"
        DB_PASSWORD: "{{ .pg_admin_password }}"
        DB_SSL__REJECT_UNAUTHORIZED: "false"
        KEY: "{{ .directus_key }}"
        SECRET: "{{ .directus_secret }}"
        ADMIN_EMAIL: "kevin@kevinryan.io"
        ADMIN_PASSWORD: "{{ .directus_admin_password }}"
        STORAGE_LOCATIONS: "azure"
        STORAGE_AZURE_DRIVER: "azure"
        STORAGE_AZURE_CONTAINER_NAME: "directus-uploads"
        STORAGE_AZURE_ACCOUNT_NAME: "{{ .directus_blob_account_name }}"
        STORAGE_AZURE_ACCOUNT_KEY: "{{ .directus_blob_account_key }}"
        PUBLIC_URL: "https://dam.kevinryan.io"
  data:
    - secretKey: pg_fqdn
      remoteRef:
        key: pg-fqdn
    - secretKey: pg_admin_username
      remoteRef:
        key: pg-admin-username
    - secretKey: pg_admin_password
      remoteRef:
        key: pg-admin-password
    - secretKey: directus_key
      remoteRef:
        key: directus-key
    - secretKey: directus_secret
      remoteRef:
        key: directus-secret
    - secretKey: directus_admin_password
      remoteRef:
        key: directus-admin-password
    - secretKey: directus_blob_account_name
      remoteRef:
        key: directus-blob-account-name
    - secretKey: directus_blob_account_key
      remoteRef:
        key: directus-blob-account-key
